create table cards
(
    id          integer generated by default as identity
        primary key,
    card_number varchar(255) not null
        constraint uk_qualp9iflk959u561wanavuj1
            unique,
    created_at  timestamp,
    exp_date    varchar(255) not null,
    name        varchar(255) not null,
    updated_at  timestamp,
    user_id     integer      not null
);